name: Automatically Build Chrome++ Lite

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include: [
            { name: Chrome++_x64, arch: x64 },
        ]

    name: ${{ matrix.name }}

    runs-on: windows-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4.1.0
      with:
        submodules: 'true'

    - name: Setup VC-LTL
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget install VC-LTL

    - name: Setup Xmake
      uses: xmake-io/github-action-setup-xmake@v1

    - name: Configure Xmake
      run: xmake f -a ${{ matrix.arch }}

    - name: Build Chrome++
      run: xmake

    - name: Upload DLL
      uses: actions/upload-artifact@v3.1.3
      with:
        name: ${{ matrix.name }}
        path: build/release
